server:
  port: 8080

spring:
  profiles:
    active: local
  jackson:
    time-zone: GMT+8

embedding:
  api:
    url: https://dashscope.aliyuncs.com/compatible-mode/v1/embeddings
    key: ${LLM_API_KEY}
vector:
  topk: 5
  threshold: 0.60

dashscope:
  api:
    url: https://dashscope.aliyuncs.com/compatible-mode/v1/embeddings # <- 替换为真实 dashscope embedding URL
    key: ${LLM_API_KEY}  # 推荐用环境变量 DASHSCOPE_API_KEY
model:
  name: "text-embedding-v2"
kb:
  raw-path: "src/main/resources/data/kb.csv"
  emb-path: "src/main/resources/data/kb_with_embedding.csv"
  correction-path: "src/main/resources/data/correction.csv"
search:
  desc-weight: 3
  name-weight: 1
